#!/usr/bin/env bash
# Print bundle identifiers and designated code requirements for PPPC authoring.
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: collect_tcc_identities.sh <app-or-binary> [...]

Outputs the bundle identifier (when present) and designated code requirement for
each supplied path. Feed these values into a PPPC profile generated by MDM or a
PPPC profile tool. Do not assume Terminal/Xcode attribution; confirm with
scripts/macos/tcc_attribution_tail.sh around the actual prompt.
USAGE
}

if [[ $# -lt 1 ]]; then
  usage >&2
  exit 2
fi

for path in "$@"; do
  if [[ ! -e "$path" ]]; then
    echo "Skipping missing path: $path" >&2
    continue
  fi

  echo "---"
  echo "path: $path"

  if [[ -d "$path" && -f "$path/Contents/Info.plist" ]]; then
    bundle_id="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$path/Contents/Info.plist" 2>/dev/null || true)"
    if [[ -n "$bundle_id" ]]; then
      echo "bundle_id: $bundle_id"
    fi
  fi

  echo "designated_requirement: |"
  if codesign -dr - "$path" >/tmp/tcc_identity_codesign.$$ 2>&1; then
    sed 's/^/  /' /tmp/tcc_identity_codesign.$$
  else
    sed 's/^/  /' /tmp/tcc_identity_codesign.$$ || true
    echo "  <codesign failed>"
  fi
  rm -f /tmp/tcc_identity_codesign.$$
done
